blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('',views.PostListView.as_view(),name='post-list'),
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='post-detail'),
    path('post/create/',views.PostCreateView.as_view(),name='create_post'),
    path('post/<int:pk>/edit/',views.PostUpdateView.as_view(),name='edit_post'),
    path('post/<int:pk>/remove/',views.PostDeleteView.as_view(),name='remove_post'),
    path('drafts/',views.DraftListView.as_view(),name='post_draft'),
    path('post/<int:pk>/publish/', views.post_publishing, name='post_publishing'),
    path('post/<int:pk>/comments', views.CommentCreateView.as_view(),name='add_comment_to_post'),
    path('comment/<int:pk>/remove', views.CommentDeleteView.as_view(), name='remove_comment'),
    path('comment/<int:pk>/approve',views.approve_comment_view,name='approve_comment'),
]

prototype/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('account.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('',include('shop.urls')),
    path('blog/',include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, include
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.ProductList.as_view(),name='products-view'),
    path('products/add/',views.CreateProduct.as_view(),name='products-add'),
    path('products/<slug:slug>/', views.ProductDetail.as_view(),name='products-detail'),
    path('products/<slug:slug>/add_to_cart/',views.add_to_cart,name='add-to-cart-view'),
    path('products/<slug:slug>/decrease_from_cart/',views.decrease_from_cart,name='decrease-from-cart-view'),
    path('products/<slug:slug>/remove_from_cart/',views.remove_from_cart,name='remove-from-cart-view'),
    path('products/delete/<slug:slug>/',views.DeleteProduct.as_view(),name='products-delete'),
    path('category/<slug:slug>',views.CategoryView.as_view(),name='category-view'),
    path('carts/', views.CartList.as_view(),name='carts-view'),
    path('carts/<int:pk>/',views.CartDetail.as_view(),name='carts-detail'),
    # path('orders/', views.OrderList.as_view(),name='orders-view'),
    path('orders/<int:pk>/',views.OrderDetail.as_view(),name='orders-detail'),
    # path('publish/',views.PublishList.as_view(),name='publish-view'),
    # path('publish/<slug:slug>/',views.PublishView.as_view(),name='publishing'),
    path('payment/<int:pk>/',views.PaymentView,name='payment-view'),
    path('wishlist/<slug:slug>',views.WishListView.as_view(),name='wishlist-view'),
    path('wishlist/add/<slug:slug>/',views.add_to_wishlist,name='add-to-wishlist'),
    path('wishlist/remove/<slug:slug>/',views.remove_from_wishlist,name='remove-from-wishlist'),
    path('checkout/',views.CheckoutTemplateView.as_view(),name='checkout-view'),
]

shop/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils import timezone

User = get_user_model()

class Category(models.Model):
    name =  models.CharField(max_length=25)
    sub_category = models.ManyToManyField('self',blank=True)
    is_main = models.BooleanField(default=False)
    slug = models.SlugField(allow_unicode=True,unique=True,blank=True)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    def __str__(self):
        return f'{self.name}'

class Product(models.Model):
    name = models.CharField(max_length=70)
    category = models.ForeignKey(Category, related_name='product_category', on_delete=models.SET_NULL, null=True)
    detail = models.CharField(max_length=150)
    slug = models.SlugField(allow_unicode=True,unique=True,blank=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to="product/")
    is_published = models.BooleanField(default=False)
    publish_time = models.DateTimeField(blank=True,null=True)

    def publish(self):
        self.is_published = True
        self.publish_time = timezone.now()
        self.save()

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('shop:products-detail',kwargs={'slug':self.slug})

    def __str__(self):
        return f'{self.name}'

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='cart_products', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def total_cart(self):
        return self.product.price * self.quantity

    def __str__(self):
        return f'{self.quantity} of {self.product.name}'

class Order(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    orderitems = models.ManyToManyField(Cart,related_name='order_items')
    created_at = models.DateTimeField(auto_now_add=True)

    def total_order(self):
        total = 0
        for order_item in self.orderitems.all():
            total += order_item.total_cart()
        return total

    def __str__(self):
        return f'{self.user.username} order {self.pk}'

class SuccessfulPayment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    orderitems = models.TextField(blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.user}'


class ProductFilter(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    price1 = models.IntegerField(blank=True, null=True)
    price2 = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f'{self.price1}-{self.price2}'

class Wishlist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    list = models.ManyToManyField(Product)
    slug = models.SlugField(allow_unicode=True,unique=True,blank=True)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.user.username)
        super().save(*args,**kwargs)

    def __str__(self):
        return f'{self.user}'

class ProductComment(models.Model):
    class Meta:
        ordering = ('is_approved','-creating_date')

    author = models.CharField(max_length=30)
    text = models.TextField(max_length=200)
    email = models.EmailField()
    # Verify_exists???
    website = models.URLField(blank=True)
    product = models.ForeignKey(Product, related_name='product_comments' ,on_delete=models.CASCADE)
    creating_date = models.DateTimeField(default=timezone.now)
    is_approved = models.BooleanField(default=False)

    def approve(self):
        self.is_approved = True
        self.save()

    def get_absolute_url(self):
        return reverse('shop:products-view')

    def __str__(self):
        return self.text

shop/forms.py
from django import forms
from .models import ProductFilter, ProductComment

class PriceFilterForm(forms.ModelForm):
    class Meta:
        model = ProductFilter
        fields = ('price1','price2')

class ProductCommentForm(forms.ModelForm):
    class Meta:
        model = ProductComment
        fields = ('author', 'email', 'website', 'text')

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.http import HttpResponse, Http404
from . import models
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .forms import PriceFilterForm, ProductCommentForm


User = get_user_model()

class ProductList(generic.ListView):
    model = models.Product
    template_name = 'shop/shop.html'
    paginate_by = 6

    def get_queryset(self):
        queryset = super().get_queryset()
        try:
            a = get_object_or_404(models.ProductFilter,user=self.request.user)
            qs = queryset.filter(price__range=(a.price1,a.price2))
            a.delete()
            return qs.filter(is_published=True).order_by('-publish_time')
        except:
            pass
        return queryset.filter(is_published=True).order_by('-publish_time')

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        # from django.db.models import Q
        # print("\n\n\n")
        # print("Puma")
        # print(models.Product.objects.filter(category__name__iexact="Puma"))
        # print("\nNot Published")
        # print(models.Product.objects.filter(is_published=True))
        # print("\n Puma.published")
        # print(models.Product.objects.filter(category__name__iexact="Puma").filter(is_published=True))
        # print("\n Puma , Published")
        # print(models.Product.objects.filter(Q(category__name__iexact="Puma")|Q(is_published=True)))
        # print("\n\n\n")
        try:
            context['main_categories'] = models.Category.objects.filter(is_main=True)
        except:
            pass
        context['price_filter_form'] = PriceFilterForm()
        return context

    def post(self, *args, **kwargs):
        if 'price1' in self.request.POST:
            form = PriceFilterForm(self.request.POST)
            if form.is_valid():
                self.object  = form.save(commit=False)
                self.object.user = self.request.user
                form.save(commit=True)
            else:
                print("*** INVALID FORM ***")
        return redirect('shop:products-view')



class ProductDetail(LoginRequiredMixin,generic.DetailView):
    model = models.Product
    template_name = 'shop/product-details.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['product_comment_form'] = ProductCommentForm()
        try:
            product = get_object_or_404(models.Product,slug=self.kwargs.get('slug'),is_published=True)
            d = models.Cart.objects.filter(user=self.request.user,product=product)
            context['quantity_by_product'] = d[0].quantity
        except:
            pass
        try:
            context['main_categories'] = models.Category.objects.filter(is_main=True)
        except:
            pass
        try:
            this_product = get_object_or_404(models.Product,slug=self.kwargs.get('slug'),is_published=True)
            pdc = models.Product.objects.filter(category__sub_category__name__exact=this_product.category.sub_category.all()[0].name).order_by('-publish_time')
            context['related_products'] = pdc[:4]
        except:
            pass
        return context

    def post(self, *args, **kwargs):
        form = ProductCommentForm(self.request.POST)
        if form.is_valid():
            productcomment = form.save(commit=False)
            product = get_object_or_404(models.Product,slug=self.kwargs['slug'])
            productcomment.product = product
            form.save(commit=True)
        else:
            print("*** INVALID FORM ***")
        return redirect('shop:products-detail', slug=self.kwargs['slug'])


class CreateProduct(LoginRequiredMixin,generic.CreateView):
    model = models.Product
    fields = ('name','category','detail','price','image')

    # def form_valid(self,form):
    #     self.object  = form.save(commit=False)
    #     self.object.user = self.request.user
    #     self.object.save()
    #     return super().form_valid(form)

class DeleteProduct(LoginRequiredMixin,generic.DeleteView):
    model = models.Product
    success_url = reverse_lazy('shop:products-view')

    def delete(self,*args,**kwargs):
        print('Product Deleted')
        return super().delete(*args,**kwargs)

class CategoryView(generic.DetailView):
    model = models.Category
    template_name = 'shop/category.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['main_categories'] = models.Category.objects.filter(is_main=True)
        except:
            pass
        return context

class WishListView(generic.DetailView):
    model = models.Wishlist
    template_name = 'shop/wishlist.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['main_categories'] = models.Category.objects.filter(is_main=True)
        except:
            pass
        return context

class CartList(LoginRequiredMixin,generic.ListView):
    model = models.Cart

class CartDetail(LoginRequiredMixin,generic.DetailView):
    model = models.Cart

class OrderList(LoginRequiredMixin,generic.ListView):
    model = models.Order

class OrderDetail(LoginRequiredMixin,generic.DetailView):
    model = models.Order
    template_name = 'shop/cart.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.request.user)

class PublishList(LoginRequiredMixin,generic.ListView):
    model = models.Product
    template_name = 'shop/publish.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(is_published=False)

class PublishView(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('shop:publish-view')

    def get(self,*args,**kwargs):
        product = get_object_or_404(models.Product,slug=self.kwargs.get('slug'))
        product.publish()
        return super().get(self.request,*args,**kwargs)

class CheckoutTemplateView(generic.TemplateView):
    template_name = 'shop/checkout.html'


@login_required
def PaymentView(request,pk):
    order = get_object_or_404(models.Order,pk=pk)
    sp, spc = models.SuccessfulPayment.objects.get_or_create(user=request.user)
    text = ''
    for i in order.orderitems.all():
        text += str(i)+'\n'
    text += '--------------\n'
    text += sp.orderitems
    sp.orderitems = text
    sp.save()
    models.Cart.objects.filter(user=request.user).delete()
    order.delete()
    return redirect('shop:orders-view')

@login_required
def add_to_cart(request,slug):
    product = get_object_or_404(models.Product,slug=slug,is_published=True)
    order_item,created_cart = models.Cart.objects.get_or_create(product=product,user=request.user)
    order_qs,created_order = models.Order.objects.get_or_create(user=request.user)
    # IS THERE AN ORDER?:
    if not created_order:
        # IS THERE A CART WITH THIS PRODUCT
        if order_qs.orderitems.filter(product__slug=product.slug).exists():
            print("add to cart ", order_item, " reuslt quantity = ", order_item.quantity+1)
            order_item.quantity += 1
            order_item.save()
        # THERE IS AN ORDER BUT NO SAME CART
        else:
            order_qs.orderitems.add(order_item)
            print("New item (", order_item ,") added to cart and now add to order ",order_qs)
    # THERE IS NO CART IN ACTIVE ORDER:
    else:
        order_qs.orderitems.add(order_item)
        print("New order (", order_qs ,") created and item (", order_item ,") added to orderitems")
    return redirect('shop:orders-detail',pk=order_qs.pk)

@login_required
def decrease_from_cart(request,slug):
    product = get_object_or_404(models.Product,slug=slug,is_published=True)
    order_item = get_object_or_404(models.Cart, product=product,user=request.user)
    order_qs = get_object_or_404(models.Order,user=request.user)

    # IS THERE A CART WITH THIS PRODUCT WITH QUANTITY OF MORE THAN 1
    if not order_qs.orderitems.filter(product__slug=product.slug).filter(quantity__lte=1).exists():
        print("decrease from cart ", order_item, " reuslt quantity = ", order_item.quantity-1)
        order_item.quantity -= 1
        order_item.save()
    # CART WITH THIS PRODUCT WITH QUANTITY OF 1
    else:
        print("Product quantity was one and the cart is deleted")
        order_item.delete()
        # IS THERE JUST ONE CART?:
        if (models.Cart.objects.filter(user=request.user).count() == 0):
            print("There was only one cart and the order is deleted")
            order_qs.delete()
            return redirect('shop:orders-view')
    return redirect('shop:orders-detail',pk=order_qs.pk)

@login_required
def remove_from_cart(request,slug):
    product = get_object_or_404(models.Product,slug=slug,is_published=True)
    models.Cart.objects.filter(user=request.user,product=product).delete()
    order = get_object_or_404(models.Order,user=request.user)
    # order = models.Order.objects.filter(user=request.user)
    if (models.Cart.objects.filter(user=request.user).count() == 0):
        order.delete()
        return redirect('shop:products-view')
    return redirect('shop:orders-detail', pk=order.pk)

@login_required
def add_to_wishlist(request,slug):
    product = get_object_or_404(models.Product,slug=slug,is_published=True)
    wishlist_item,is_created = models.Wishlist.objects.get_or_create(user=request.user)
    wishlist_item.list.add(product)
    return redirect('shop:wishlist-view', slug=request.user.username)

@login_required
def remove_from_wishlist(request,slug):

templates/shop/cart.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
	<section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="{% url 'shop:products-view' %}">Home</a></li>
				  <li class="active">Shopping Cart</li>
				</ol>
			</div>
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="description"></td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
            {% for item in order.orderitems.all %}
  						<tr>
  							<td class="cart_product">
  								<a href="{% url 'shop:products-detail' slug=item.product.slug %}"><img style="height:50px;" src="../../../media/{{ item.product.image }}" alt=""></a>
  							</td>
  							<td class="cart_description">
  								<h4><a href="{% url 'shop:products-detail' slug=item.product.slug %}">{{ item.product.name }}</a></h4>
  								<p>Web ID: 1089772</p>
  							</td>
  							<td class="cart_price">
  								<p>{{ item.product.price }}</p>
  							</td>
  							<td class="cart_quantity">
  								<div class="cart_quantity_button">
  									<a class="cart_quantity_up" href="{% url 'shop:add-to-cart-view' slug=item.product.slug %}"> + </a>
  									<input class="cart_quantity_input" type="text" name="quantity" value="{{ item.quantity }}" autocomplete="off" size="2">
  									<a class="cart_quantity_down" href="{% url 'shop:decrease-from-cart-view' slug=item.product.slug %}"> - </a>
  								</div>
  							</td>
  							<td class="cart_total">
  								<p class="cart_total_price">${{ item.total_cart}}</p>
  							</td>
  							<td class="cart_delete">
  								<a class="cart_quantity_delete" href="{% url 'shop:remove-from-cart-view' slug=item.product.slug %}"><i class="fa fa-times"></i></a>
  							</td>
  						</tr>
            {% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</section> <!--/#cart_items-->

	<section id="do_action">
		<div class="container">
			<div class="heading">
				<h3>What would you like to do next?</h3>
				<p>Choose if you have a discount code or reward points you want to use or would like to estimate your delivery cost.</p>
			</div>
			<div class="row">
				<div class="col-sm-6">
					<div class="chose_area">
						<ul class="user_option">
							<li>
								<input type="checkbox">
								<label>Use Coupon Code</label>
							</li>
							<li>
								<input type="checkbox">
								<label>Use Gift Voucher</label>
							</li>
							<li>
								<input type="checkbox">
								<label>Estimate Shipping & Taxes</label>
							</li>
						</ul>
						<ul class="user_info">
							<li class="single_field">
								<label>Country:</label>
								<select>
									<option>United States</option>
									<option>Bangladesh</option>
									<option>UK</option>
									<option>India</option>
									<option>Pakistan</option>
									<option>Ucrane</option>
									<option>Canada</option>
									<option>Dubai</option>
								</select>

							</li>
							<li class="single_field">
								<label>Region / State:</label>
								<select>
									<option>Select</option>
									<option>Dhaka</option>
									<option>London</option>
									<option>Dillih</option>
									<option>Lahore</option>
									<option>Alaska</option>
									<option>Canada</option>
									<option>Dubai</option>
								</select>

							</li>
							<li class="single_field zip-field">
								<label>Zip Code:</label>
								<input type="text">
							</li>
						</ul>
						<a class="btn btn-default update" href="">Get Quotes</a>
						<a class="btn btn-default check_out" href="">Continue</a>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="total_area">
						<ul>
							<li>Cart Sub Total <span>${{ order.total_order }}</span></li>
							<li>Eco Tax <span>Free</span></li>
							<li>Shipping Cost <span>Free</span></li>
							<li>Total <span>${{ order.total_order }}</span></li>
						</ul>
							<a class="btn btn-default update" href="">Update</a>
							<a class="btn btn-default check_out" href="{% url 'shop:payment-view' pk=order.pk %}">Check Out</a>
					</div>
				</div>
			</div>
		</div>
	</section><!--/#do_action-->
{% endblock content %}

templates/shop/category.html
{% extends "base/base.html" %}
{% load static %}
{% load cart_tag %}
{% block content %}
<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <div class="left-sidebar">
          <h2>Category</h2>
          <div class="panel-group category-products" id="accordian"><!--category-productsr-->
            {% for cat in main_categories %}
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordian" href="#{{ cat|lower }}">
                      {% if cat.sub_category.all %}
                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                      {% endif %}
                      {{ cat }}
                    </a>
                  </h4>
                </div>
                {% if cat.sub_category.all %}
                  <div id="{{ cat|lower }}" class="panel-collapse collapse">
                    <div class="panel-body">
                      <ul>
                        {% for sub_cat in cat.sub_category.all %}
                          <li><a href="{% url 'shop:category-view' slug=sub_cat.slug %}">{{ sub_cat }} </a></li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                {% endif %}
              </div>
            {% endfor %}
          </div><!--/category-productsr-->

          <div class="brands_products"><!--brands_products-->
            <h2>Brands</h2>
            <div class="brands-name">
              <ul class="nav nav-pills nav-stacked">
                <li><a href=""> <span class="pull-right">(50)</span>Acne</a></li>
                <li><a href=""> <span class="pull-right">(56)</span>Grüne Erde</a></li>
                <li><a href=""> <span class="pull-right">(27)</span>Albiro</a></li>
                <li><a href=""> <span class="pull-right">(32)</span>Ronhill</a></li>
                <li><a href=""> <span class="pull-right">(5)</span>Oddmolly</a></li>
                <li><a href=""> <span class="pull-right">(9)</span>Boudestijn</a></li>
                <li><a href=""> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
              </ul>
            </div>
          </div><!--/brands_products-->

          <div class="price-range"><!--price-range-->
            <h2>Price Range</h2>
            <div class="well">
               <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
               <b>$ 0</b> <b class="pull-right">$ 600</b>
            </div>
          </div><!--/price-range-->

          <div class="shipping text-center"><!--shipping-->
            <img src="{% static 'images/home/shipping.jpg' %}" alt="" />
          </div><!--/shipping-->

        </div>
      </div>

      <div class="col-sm-9 padding-right">
        <div class="features_items"><!--features_items-->
          <h2 class="title text-center">{{ category.name }}</h2>
          {% for product in category.product_category.all|ordering_product_by_time %}
            {% if product.is_published %}
              <a href="{% url 'shop:products-detail' slug=product.slug %}">
                <div class="col-sm-4">
                  <div class="product-image-wrapper">
                    <div class="single-products">
                      <div class="productinfo text-center">
                        <img src="../../media/{{ product.image }}" alt="" />
                        <h2>{{ product.price }}</h2>
                        <p>{{ product.name }}</p>
                        {% for top_cat in product.category.sub_category.all %}
                            <p>{{  product.category }} ({{ top_cat }})</p>
                        {% endfor %}
                        <a href="{% url 'shop:add-to-cart-view' slug=product.slug %}"><i class="fa fa-shopping-cart"></i> Add to cart</a>
                        {% comment %} <a href="remove/{{ product.slug }}" class="btn btn-danger add-to-cart"><i class="fa fa-times"></i>Remove from cart</a> {% endcomment %}
                      </div>
                      {% comment %} <div class="product-overlay">
                        <div class="overlay-content">
                          <h2>{{ product.price }}</h2>
                          <p>{{ product.name }}</p>
                          <p>{{  product.preview_text }}</p>
                          <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                        </div>
                      </div> {% endcomment %}
                    </div>
                    <div class="choose">
                      <ul class="nav nav-pills nav-justified">
                        <li><a href="{% url 'shop:add-to-wishlist' slug=product.slug %}"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                        <li><a href=""><i class="fa fa-plus-square"></i>Add to compare</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </a>
            {% endif %}
          {% endfor %}


          <ul class="pagination">
            <li class="active"><a href="">1</a></li>
            <li><a href="">2</a></li>
            <li><a href="">3</a></li>
            <li><a href="">&raquo;</a></li>
          </ul>
        </div><!--features_items-->
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/shop/comment_form.html
{% extends "blog/base.html" %}
{% block import %}
  <div class="jumbotron">
    <form class="form-group" method="POST">
      {{ form.as_p }}
      {% csrf_token %}
      <button class="btn btn-success" type="submit">Send</button>
    </form>
  </div>
{% endblock %}